export const data = [
  {
    _id: "test",
    manufacturer: "יונדאי",
    model: "איוניק",
    year: "2022",
    category: "family",
    price: "199900",
    subModels: [
      {
        name: "Prestige",
        safety: 7,
        motorType: "electric",
        volume: 160,
        horsePower: 217,
        momentum: 35.7,
        isAutoGear: true,
        breakesSystem: "מערכת כפולה מוגברת",
        breakesFront: "דיסק מאוורר",
        breakesBack: "דיסק",
        suspensionsFront: "עצמאי מסוג מקפרסון, קפיצי סליל ומוט מייצב",
        suspensionsBack: "עצמאיים מסוג Multi-Link",
        height: 1647,
        width: 1890,
        trunk: 531,
        clearance: 160,
        features: {
          isMagnezioumWheels: true,
          isPanoramicRoof: true,
          isMultimediaSystem: true,
          isCarPlay: true,
          isLeatherCovers: false,
          isDigitalClocks: true,
          isStartButton: true,
          isElectricHandBreaks: true,
        },
      },
      {
        name: "Supreme",
        safety: 7,
        motorType: "electric",
        volume: 160,
        horsePower: 217,
        momentum: 35.7,
        isAutoGear: true,
        breakesSystem: "מערכת כפולה מוגברת",
        breakesFront: "דיסק מאוורר",
        breakesBack: "דיסק",
        suspensionsFront: "עצמאי מסוג מקפרסון, קפיצי סליל ומוט מייצב",
        suspensionsBack: "עצמאיים מסוג Multi-Link",
        height: 1647,
        width: 1890,
        trunk: 531,
        clearance: 160,
        features: {
          isMagnezioumWheels: true,
          isPanoramicRoof: true,
          isMultimediaSystem: true,
          isCarPlay: true,
          isLeatherCovers: false,
          isDigitalClocks: true,
          isStartButton: true,
          isElectricHandBreaks: true,
        },
      },
      {
        name: "Elite",
        safety: 7,
        motorType: "electric",
        volume: 160,
        horsePower: 305,
        momentum: 61.7,
        isAutoGear: true,
        breakesSystem: "מערכת כפולה מוגברת",
        breakesFront: "דיסק מאוורר",
        breakesBack: "דיסק",
        suspensionsFront: "עצמאי מסוג מקפרסון, קפיצי סליל ומוט מייצב",
        suspensionsBack: "עצמאיים מסוג Multi-Link",
        height: 1647,
        width: 1890,
        trunk: 531,
        clearance: 160,
        features: {
          isMagnezioumWheels: true,
          isPanoramicRoof: true,
          isMultimediaSystem: true,
          isCarPlay: true,
          isLeatherCovers: true,
          isDigitalClocks: true,
          isStartButton: true,
          isElectricHandBreaks: true,
        },
      },
    ],
  },
  // {
  //     _id: "c101",
  //     manufacturer: "יונדאי",
  //     model: "איוניק",
  //     type: "family",
  //     price: "199900",
  //     height: 1647,
  //     trunk: 531,
  //     horsePower: 217,
  //     isGearAuto: true,
  //     safety: 7,
  //     isElectric: true,
  //     features: {
  //         isMagnezioumWheels: true,
  //         isPanoramicRoof: true,
  //         isMultimediaSystem: true,
  //         isCarPlay: true,
  //         isLeatherCovers: false,
  //         isDigitalClocks: true,
  //         isStartButton: true,
  //         isElectricHandBreaks: true
  //     }
  // },
  // {
  //     _id: "c102",
  //     manufacturer: "יונדאי",
  //     model: "קונה EV",
  //     type: "family",
  //     price: "148900",
  //     height: 1570,
  //     trunk: 332,
  //     horsePower: 136,
  //     isGearAuto: true,
  //     safety: 7,
  //     isElectric: true,
  //     features: {
  //         isMagnezioumWheels: true,
  //         isPanoramicRoof: false,
  //         isMultimediaSystem: true,
  //         isCarPlay: true,
  //         isLeatherCovers: false,
  //         isDigitalClocks: true,
  //         isStartButton: true,
  //         isElectricHandBreaks: true
  //     }
  // },
  // {
  //     _id: "c103",
  //     manufacturer: "יונדאי",
  //     model: "אלנטרה הייבריד",
  //     type: "executive",
  //     price: "152900",
  //     height: 1420,
  //     trunk: 474,
  //     motor: 1.6,
  //     gasType: "benzin",
  //     horsePower: 105,
  //     safety: 6,
  //     gasUsage: 4.4,
  //     isGearAuto: true,
  //     isElectric: true,
  //     features: {
  //         isMagnezioumWheels: true,
  //         isPanoramicRoof: true,
  //         isMultimediaSystem: true,
  //         isCarPlay: true,
  //         isLeatherCovers: false,
  //         isDigitalClocks: true,
  //         isStartButton: true,
  //         isElectricHandBreaks: true
  //     }
  // },
  // {
  //     _id: "c104",
  //     manufacturer: "יונדאי",
  //     model: "אלנטרה וניו",
  //     type: "suv",
  //     price: "113900",
  //     motor: 1.6,
  //     gasType: "benzin",
  //     horsePower: 123,
  //     height: 1892,
  //     trunk: 355,
  //     safety: 6,
  //     gasUsage: 6.6,
  //     isGearAuto: true,
  //     isElectric: false,
  //     features: {
  //         isMagnezioumWheels: true,
  //         isPanoramicRoof: false,
  //         isMultimediaSystem: true,
  //         isCarPlay: true,
  //         isLeatherCovers: false,
  //         isDigitalClocks: true,
  //         isStartButton: false,
  //         isElectricHandBreaks: false
  //     }
  // },
  // {
  //     _id: "c105",
  //     manufacturer: "יונדאי",
  //     model: "טוסון",
  //     type: "family",
  //     price: "166900",
  //     motor: 2,
  //     gasType: "benzin",
  //     horsePower: 156,
  //     height: 1650,
  //     trunk: 515,
  //     safety: 6,
  //     gasUsage: 8.2,
  //     isGearAuto: true,
  //     isElectric: false,
  //     features: {
  //         isMagnezioumWheels: true,
  //         isPanoramicRoof: true,
  //         isMultimediaSystem: true,
  //         isCarPlay: true,
  //         isLeatherCovers: false,
  //         isDigitalClocks: true,
  //         isStartButton: true,
  //         isElectricHandBreaks: true
  //     }
  // },
  // {
  //     _id: "c106",
  //     manufacturer: "יונדאי",
  //     model: "i10",
  //     type: "mini",
  //     price: "82900",
  //     motor: 1.2,
  //     gasType: "benzin",
  //     horsePower: 84,
  //     height: 1480,
  //     trunk: 252,
  //     safety: 6,
  //     gasUsage: 4.2,
  //     isGearAuto: true,
  //     isElectric: false,
  //     features: {
  //         isMagnezioumWheels: false,
  //         isPanoramicRoof: false,
  //         isMultimediaSystem: true,
  //         isCarPlay: true,
  //         isLeatherCovers: false,
  //         isDigitalClocks: false,
  //         isStartButton: false,
  //         isElectricHandBreaks: false
  //     }
  // },
  // {
  //     _id: "c107",
  //     manufacturer: "יונדאי",
  //     model: "קונה הייבריד",
  //     type: "family",
  //     price: "149900",
  //     motor: 1.6,
  //     gasType: "benzin",
  //     horsePower: 139,
  //     height: 1550,
  //     trunk: 374,
  //     safety: 6,
  //     gasUsage: 3.9,
  //     isGearAuto: true,
  //     isElectric: true,
  //     features: {
  //         isMagnezioumWheels: true,
  //         isPanoramicRoof: false,
  //         isMultimediaSystem: true,
  //         isCarPlay: true,
  //         isLeatherCovers: false,
  //         isDigitalClocks: true,
  //         isStartButton: true,
  //         isElectricHandBreaks: true
  //     }
  // },
  // {
  //     _id: "c108",
  //     manufacturer: "יונדאי",
  //     model: "קונה",
  //     type: "family",
  //     price: "131900",
  //     motor: 1.6,
  //     gasType: "benzin",
  //     horsePower: 198,
  //     height: 1550,
  //     trunk: 374,
  //     safety: 6,
  //     gasUsage: 6.6,
  //     isGearAuto: true,
  //     isElectric: true,
  //     features: {
  //         isMagnezioumWheels: true,
  //         isPanoramicRoof: false,
  //         isMultimediaSystem: true,
  //         isCarPlay: true,
  //         isLeatherCovers: false,
  //         isDigitalClocks: true,
  //         isStartButton: true,
  //         isElectricHandBreaks: false
  //     }
  // },
  // {
  //     _id: "c109",
  //     manufacturer: "יונדאי",
  //     model: "סונטה הייבריד",
  //     type: "executive",
  //     price: "201900",
  //     motor: 2,
  //     gasType: "benzin",
  //     horsePower: 192,
  //     height: 1445,
  //     trunk: 510,
  //     safety: 7,
  //     gasUsage: 5,
  //     isGearAuto: true,
  //     isElectric: true,
  //     features: {
  //         isMagnezioumWheels: true,
  //         isPanoramicRoof: false,
  //         isMultimediaSystem: true,
  //         isCarPlay: true,
  //         isLeatherCovers: true,
  //         isDigitalClocks: true,
  //         isStartButton: true,
  //         isElectricHandBreaks: true
  //     }
  // },
  // {
  //     _id: "c110",
  //     manufacturer: "יונדאי",
  //     model: "סונטה טורבו",
  //     type: "executive",
  //     price: "189900",
  //     motor: 1.6,
  //     gasType: "benzin",
  //     horsePower: 180,
  //     height: 1445,
  //     trunk: 510,
  //     safety: 7,
  //     gasUsage: 7.6,
  //     isGearAuto: true,
  //     isElectric: true,
  //     features: {
  //         isMagnezioumWheels: true,
  //         isPanoramicRoof: false,
  //         isMultimediaSystem: true,
  //         isCarPlay: true,
  //         isLeatherCovers: true,
  //         isDigitalClocks: true,
  //         isStartButton: true,
  //         isElectricHandBreaks: true
  //     }
  // },
  // {
  //     _id: "c111",
  //     manufacturer: "יונדאי",
  //     model: "i20",
  //     type: "mini",
  //     price: "108900",
  //     motor: 1,
  //     gasType: "benzin",
  //     horsePower: 100,
  //     height: 1450,
  //     trunk: 352,
  //     safety: 6,
  //     gasUsage: 5.7,
  //     isGearAuto: true,
  //     isElectric: false,
  //     features: {
  //         isMagnezioumWheels: false,
  //         isPanoramicRoof: false,
  //         isMultimediaSystem: true,
  //         isCarPlay: true,
  //         isLeatherCovers: false,
  //         isDigitalClocks: true,
  //         isStartButton: false,
  //         isElectricHandBreaks: false
  //     }
  // },
  // {
  //     _id: "c112",
  //     manufacturer: "יונדאי",
  //     model: "סנטה פה",
  //     type: "SUV",
  //     price: "269900",
  //     motor: 2.2,
  //     gasType: "dizel",
  //     horsePower: 202,
  //     height: 1710,
  //     trunk: 571,
  //     safety: 8,
  //     gasUsage: 6.3,
  //     isGearAuto: true,
  //     isElectric: false,
  //     features: {
  //         isMagnezioumWheels: true,
  //         isPanoramicRoof: true,
  //         isMultimediaSystem: true,
  //         isCarPlay: true,
  //         isLeatherCovers: false,
  //         isDigitalClocks: true,
  //         isStartButton: true,
  //         isElectricHandBreaks: true
  //     }
  // },
  // {
  //     _id: "c113",
  //     manufacturer: "יונדאי",
  //     model: "פאליסאדה",
  //     type: "SUV",
  //     price: "319900",
  //     motor: 3.8,
  //     gasType: "benzin",
  //     horsePower: 291,
  //     height: 1750,
  //     trunk: 311,
  //     safety: 8,
  //     gasUsage: 11.1,
  //     isGearAuto: true,
  //     isElectric: false,
  //     features: {
  //         isMagnezioumWheels: true,
  //         isPanoramicRoof: true,
  //         isMultimediaSystem: true,
  //         isCarPlay: true,
  //         isLeatherCovers: true,
  //         isDigitalClocks: true,
  //         isStartButton: true,
  //         isElectricHandBreaks: true
  //     }
  // },
  // {
  //     _id: "c114",
  //     manufacturer: "יונדאי",
  //     model: "באיון",
  //     type: "family",
  //     price: "123900",
  //     motor: 1,
  //     gasType: "benzin",
  //     horsePower: 100,
  //     height: 1500,
  //     trunk: 373,
  //     safety: 6,
  //     gasUsage: 5.5,
  //     isGearAuto: true,
  //     isElectric: false,
  //     features: {
  //         isMagnezioumWheels: true,
  //         isPanoramicRoof: false,
  //         isMultimediaSystem: true,
  //         isCarPlay: true,
  //         isLeatherCovers: true,
  //         isDigitalClocks: true,
  //         isStartButton: true,
  //         isElectricHandBreaks: false
  //     }
  // },
];

export const questionnaireDynamicCmps = {
    CarType: {
        cmpClassName: "type-pick",
        containerClassName: "types-container",
        header: "איזה סוג רכב אתה מעדיף?",
        subHeader: "*ניתן לבחור יותר מסוג אחד",
        data: ["מנהלים", "משפחתי", "קטן", "פנאי ושטח", "מסחרי", "ספורט", "יוקרה", "מיניואן"],
        stateName: "carTypes",
        isLimitedPicks: false,
        nextSection: "FeaturesPick"
    },
    FeaturesPick: {
        cmpClassName: "features-pick",
        containerClassName: "features-container",
        header: "מה חשוב לך ברכב?",
        subHeader: "ניתן לבחור עד 3 מאפיינים",
        data: ['בטיחות', 'ביצועים', 'חיסכון בדלק', 'אבזור', 'מרחב', 'תא מטען גדול', 'נוחות', 'רכב גבוה'],
        stateName: "threeImportantFeaturs",
        isLimitedPicks: true,
        nextSection: "AccessoriesPick",
    },
    AccessoriesPick: {
        cmpClassName: "accessories-pick",
        containerClassName: "accessories-container",
        header: "מה מהדברים הבאים חשובים לך מבחינת אבזור?",
        subHeader: false,
        data: ['גלגלי מגנזיום', 'מערכת מולטימדיה', 'CAR PLAY', 'גג פנורמי/נפתח', 'ריפודי עור', 'לוח מחוונים דיגטלי', 'כניסה והנעה ללא מפתח', 'בלם יד חשמלי'],
        stateName: "importantAccessories",
        isLimitedPicks: false,
        nextSection: "LuggagePick",
    },
    LuggagePick: {
        cmpClassName: "luggage-pick",
        containerClassName: "luggage-container",
        header: "סמן את הדברים שתרצה להכניס לרכב",
        subHeader: "*ניתן לבחור יותר מפריט אחד",
        data: ['עגלת תינוק', 'כיסא תינוק', 'קניות', 'נוסעים מרובים', 'ציוד קמפינג', 'מזוודה', 'עוד משהו?', 'עוד משהו?'],
        stateName: "luggageTypes",
        isLimitedPicks: false,
        nextSection: "GearboxPick",
    }
}




